spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp  main:    allow-bean-definition-overriding: true
  profiles:    active:    - c3p0    da:    user: root
    password: gjw123
    jdbcUrl: jdbc:mysql://localhost:3307/userrolepri?useSSL=false&serverTimezone=Asia/Shanghai
    driverClass: com.mysql.cj.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    datasourceName: dataSource
    acquireIncrement: 4
      http:    encoding:      force: true      charset: utf-8
  redis:
    jedis:      pool:        max-active: 10
        max-idle: 5
        max-wait: 5    host: 127.0.0.1
    port: 6379
    timeout: 30000
    


mybatis:  config-location: classpath:/conf/mybatis.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  


    